first_number = int(input("Enter First number :"))
second_number = int(input("Enter second number :"))
add = first_number + second_number
subtract = first_number - second_number
multip = first_number * second_number
divid = first_number / second_number
print("Addition = ",add)
print("Subtraction = ",subtract)
print("Multiplication = ",multip)
print("Divison = ",divid)